CREATE ROLE api LOGIN PASSWORD 'api_pwd';

GRANT USAGE ON SCHEMA chloramine TO api;
GRANT SELECT ON ALL TABLES IN SCHEMA chloramine TO api;

GRANT USAGE ON SCHEMA chlorine_dioxide TO api;
GRANT SELECT ON ALL TABLES IN SCHEMA chlorine_dioxide TO api;

GRANT USAGE ON SCHEMA free_chlorine TO api;
GRANT SELECT ON ALL TABLES IN SCHEMA free_chlorine TO api;

GRANT USAGE ON SCHEMA ozone TO api;
GRANT SELECT ON ALL TABLES IN SCHEMA ozone TO api;
