name: Run E2E tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache node_modules and cypress
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            web/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('web/pnpm-lock.yaml') }}

      - name: Install dependencies if uncached
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build:node

      - name: Serve
        run: pnpm run preview:node &

      - name: Run tests
        run: pnpm run test:preview
